[package]
name = "http_server"
version = "0.1.0"
edition = "2021"

[features]
default = ["futures-lite"]
futures = ["dep:futures"]
futures-lite = ["dep:futures-lite"]

[dependencies]
# async
futures = { version = "0.3.0", optional = true }
futures-lite = { version =  "2.3.0", optional = true }
async-io = "2.3.4"
async-trait = "0.1.81"
# http
http = "1.0.0"
# logging
log = "0.4.20"

[dev-dependencies]
env_logger = "0.11.5"